---

- name: Download helm install script
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    owner: root
    group: root
    mode: "0700"

- name: Execute helm install script
  become: "yes"
  ansible.builtin.command: bash /tmp/get_helm.sh

- name: Install python kubernetes core pre-requisites
  ansible.builtin.pip:
    name:
      - jsonpatch
      - pyyaml
      - kubernetes
      - kubernetes-validate

- name: Install git
  become: "yes"
  ansible.builtin.package:
    name:
      - git
    state: present

- name: Install helm diff
  ignore_errors: "yes"
  ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff